### ISSUE TITLE
Question on newreply.go

### ISSUE THREAD

**Issue by imageboards** [rls-moe/nyx#10]
So i see that lots of your files require external things, like newreoly.go calls ::

"github.com/pressly/chi"
	"github.com/tidwall/buntdb"
	"go.rls.moe/nyx/config"
	"go.rls.moe/nyx/http/errw"
	"go.rls.moe/nyx/http/middle"
	"go.rls.moe/nyx/resources"

//////////

New to GO- pls keep that in mind. So my question is, if the github account pressly/chi or your site @ "go.rls.moe/nyx is discontinued, that would render new installs of the imageboard inoperable, because the code dependencies are not there to call from right?

**Comment by bryanpedini** [comment]
Wrong, you didn't get what Go packages are, at all.
Those dependencies are used at compile time, when you have a binary executable it's all self-contained and it will work until the general architecture of the underlying operating system changes so drammatically that the executable file format changes as well.

**Comment by bryanpedini** [comment]
PS: we saw your profile, you're basically an archive made of forks of other projects which you never even touch, you just fork and admire them (for what reason, well that is unknown). Of course you're new to Go, you just cloned a bunch of stuff and IDK, pretend to have made all of them (?).

CC @tscs37 sorry the ping again, could you close&limit this **other** spammer's issue too? Thanks in advance!

**Comment by imageboards** [comment]
> PS: we saw your profile, >

Who is "we"  .... you and the hand puppet that you talk to all day long?

**Comment by tscs37** [comment]
I am not a hand puppet so please don't. @bryanpedini Should I archive the repo? I've not been working on this for quite a while, not been working in go for quite a while either. The project as is is largely done, not much I would add to it.

**Comment by bryanpedini** [comment]
> @bryanpedini Should I archive the repo?

Please don't 😅 
Nyx is a stupidly simple project perfect for me to learn Go and expand on, like the TODOs and possibly even more. I tried with other Go stuff but to me they're all so complicated, so no... Perhaps if there's nothing else so important in the `rls-moe` organization, you could add me to it so that this fricking guy doesn't bother you so much (or at least I don't have to CC you to close the issues 😃).
