### ISSUE TITLE
relocation target runtime.support_avx not defined

### ISSUE THREAD

**Issue by bryanpedini** [rls-moe/nyx#3]
After solving #1 (with PR #2), I finally tried to build the project and who knew another problem arised...

This one tho seems I'm not able to either understand or solve correctly:

    # go.rls.moe/nyx
    go.rls.moe/nyx/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
    go.rls.moe/nyx/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined

This issue will need to be taken by the original author, and I cannot help with it.
I've already searched online and it suggests that the problem has to do with wrapping and the CPU detection features of the crypto library, which, having never used it, I don't know even how it works, let alone solve a problem with it.

**Comment by tscs37** [comment]
I'll have to look at this tomorrow. The library probably expects AVX to be supported but I'm not entirely certain since I haven't done anything larger in Go since I finished this project. I'm somewhat surprised someone is still interested in a project not maintained for 3 years but I'm very much going to look into this and see if I can fix it, don't like my code being broken.

**Comment by bryanpedini** [comment]
Sure thing, I too don't like my code being broken, even after time passes.

By the way, I'm still interested because I have the absolute need to put up an image board with no javascript at all (to be sure nobody, even the stupidest person, will let it's real IP address to be leaked, when working under the Tor network).

**Comment by tscs37** [comment]
I've pushed an update of external dependencies, that should fix the issue. Was probably related to changes in the go crypto libs.

**Comment by bryanpedini** [comment]
I don't know if it's my environment or what, but unfortunately both `git clone`-ing (and `go build`ing) and `go get`ting the source code, return the same error from before on blake2b.
I also made sure to have deleted the entire project from my drive and downloaded a new copy, and checked the git log to make sure the last commit by you pushed was there; nothing...

Perhaps you could setup Drone or Travis to test the builds as soon as you push (plus a couple of minutes) to avoid these long polling to get results. (and that could even create a binary build suitable to be distributed on GitHub aswell, so people don't even have to install go either)

**Comment by tscs37** [comment]
Hi, I've added a .drone.yml that runs on my local infra and it builds there after reproducing the error again; go mod didn't properly pull a modern version of golang.org/x/crypto.

**Comment by bryanpedini** [comment]
Fixed #2 now.
Thanks a lot @tscs37!!
