### ISSUE TITLE
go.mod: I would like, according to Article 15 is not used in this module.

### ISSUE THREAD

**Issue by bryanpedini** [rls-moe/nyx#4]
According to the Go extension of VSCode:
![Screenshot_20200420_205801](https://user-images.githubusercontent.com/45012292/79788935-b4f49300-8349-11ea-8f8d-b61b948ad860.png)

Is this fixable by simpling removing the line?

**Comment by tscs37** [comment]
should be addressed in the latest commit.

**Comment by bryanpedini** [comment]
And that is what it happens when you have 3 virtual machines opened at once, with shared clipboard between GDPR emails and personal pushes for fun on FOSS projects on GitHub...
Renamed the issue for future better comprehension.
