### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by imageboards** [rls-moe/nyx#9]
nyx is really nice! It still works fine. I made the db into a text file and it got super large cuz of the base 64 image code. Is there a safe/ easy way to disable image posting? That would make this a text board, but a very fast one!

**Comment by bryanpedini** [comment]
Title: `s/hi/how to disable images?/`

Response: since this is an imageboard, there is hardly no way (currently) to disable images. It could be a ToDo feature, but since there is a lot more stuff to do, I don't (personally) think it'll be a priority one.

PRs are welcome tho 😉

**Comment by imageboards** [comment]
Nyx is amazing--- blazing fast. Seems that ppl could find it useful as a blog engine, or web cms as well. fchan.xyz and gochan.org are full featured boards but way too complicated for a beginner like me to fork. Let me know if you are ever up to making some slight mods to nyx. I am literally starting at zero... i never coded GO before. You could probably do the changes that I dream about in a few minutes. I am looking 2 start a site, and i will try to learn GO so I can one day fork nyx. I would be happy to pay in case you ever wanted to make the slight mods...it would save me an incredible amount of time and allow the use of it in production for a special website project I am starting. Either way, thank you so much for coding NYX... it is truly amazing.

**Comment by bryanpedini** [comment]
CC @tscs37 can you please close and lock this spammer issue?
Thanks!
